### ISSUE TITLE
layout error when using formatselect

### ISSUE THREAD

**Issue by davetropeano** [michaelpapworth/tinymce-knockout-binding#6]
When you use the formatselect toolbar option there is an initial layout error with the tinymce control. You get some added width to the editor container. 

When you pull down the Format button and move through the options with the mouse the control resizes itself and removes the extra area :)

http://jsfiddle.net/davetropeano/ayhf9/

**Comment by michaelpapworth** [comment]
@davetropeano Is this is browser specific issue?  Your JSFiddle didn't seem to reproduce the behaviour for me.  Also, given the nature of the issue you described, I would suggest that this may be a bug in editor itself.  In which case you may find it useful to search for similar issues http://www.tinymce.com/develop/bugtracker_bugs.php

**Comment by davetropeano** [comment]
@michaelpapworth I checked it yesterday on FF and Chrome for win7 and osx, also for IE11 on win8 and it appeared each time... But I cannot duplicate it now running the fiddle.

It does seem to be an init issue with the editor which I why I raised the issue here. But since I cannot reproduce I'll close until this race condition pops up again.
